export const EnvironmentConstant = {
  DATABASE_USERNAME: 'DATABASE_USERNAME',
  DATABASE_NAME: 'DATABASE_NAME',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_HOST: 'DATABASE_HOST',
  JWT_SECRET: 'JWT_SECRET'
};
